# Generated by Django 3.1.3 on 2021-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='description',
            field=models.TextField(default='description', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='following',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
